language: ruby
rvm:
- jruby-19mode
addons:
  code_climate:
    repo_token:
      secure: "TLe3pLBEzPhv3vF07NNrQ5v8gBZypv4HRyfYUPowkEd4/1ZE2f3FdoHbGWSxE4Yupq3XIo9kMItgUMWWBLhDfmykEAUZVx/t9gDHHznMC6bKiMx8da/L2/s/icApa4CdnzoSgq0WmhE8q+3CinDDAmIVOR8tqC/YqcZs+2SEV0man7ecUi4G5rQVShse8wkEKYvNpyvvBJrWlR9TCHNajd/KrfV/b50jHvkNIgMG+1gZ06Dbn4a4ujPrP3BAIvWFUa+gKwnjZHVmvC0B28JSyDpndNp2VHRa8Y8Mhyapiwki2z90GIIj9oKdbgGWkhK4JYEsMcarj9umqZxADFwtNykJsjcOBD0cXG50413d2xObn5O9RnaEZmh3HGQurocwZkA+V0h+KT7N/lKDfdlAWw+Kn0kYP3RPWLRACwu/rYB0yyV6T4KcRSHmNbZwnjgDKVtlMOKFYWr7oC5O+78zSbrg2+V8pOlqGvSh/PnDFrm4aYGPtVrPsVObQSzkyfTgELmdilFQOox8/jAzeOjq1eeff+Y3SEulVCqjRWEiwXFAKtyxOkAtfK7aNfSOOc3RSiKPhugz7sPdeZ/c7zPfzzUPXNklJumLi41onJKNbrrrLBcBeCVpLnhvDzlvg329iFVJAFwcpRBj5nJYCHxcTbWrqt0e/SRIhNZ3s0cnEzM="
notifications:
  slack:
    secure: "QRZ6zQxcRdN2XylIz+b46TbYIv7x5Ko7Y0Mi0aGbf7Wg1xfnS4X2FZKp8gF+RH1qjT6CYsQFUpPBhPVCMx0fP0ik5/gBrdngrj0htludvQ5CTK2oVegM1VC5NSn+gi8bt2F20Ode9fxU5OS1HDzNR9sjPz3W7miMUNDZoYPy77Om/CvmVkBbGyMkWnfwhEvwnL8JpBNpklDvrUUKznNsAcSbKQBMBAglFMds/OaHXCkK142zMbSlHMctch1VDAKhX9/6M3v8v6ZRheX68+VVCz3nTrTF0/lnYh3ig9ey3DNlgkZUqK2gmypnhTE6tpeibHdyVa8qOMNzyAgltu1qIhFHN390WMk9gZXEcvWG3m++PMAIKKtd4varbH1vdCeHOGUV7GRgarcfSMvJ54I9xc5GkUnAhjRKj8xDzYzhkXwApD8eqWb2RgGXUm6G4cKj0MeQ4WBqHr9FOW/4EJcZoztFi0YlP7KE+6xptBJU479KSsv31BwHrMfblObOOj58C7gUfdbTCByxng0u1axxvixL8zJwgHvFND3/4yoXoCCgm0DXBPbi6B5xpt8QmN6K4E5sMGrppTI7VwJqkcwkVD0EEeCedRNiWLTaxlKpLYxYnoXwEnpm9o2WXWa+PjkWeawsnJvV5IAt6oJhaK22VqJN86Macuu+nCdeF1/0TZU="
jdk:
- oraclejdk8
